Configuration: moved configuration to .slashrc and updated BasicTests and PerformanceBaseTest accordingly

diff --git a/run b/run
--- a/run
+++ b/run
@@ -11,67 +11,66 @@ is_connected=1
 case $mode in 
 	
 	wifi )
-		ip=$1 # second argument is ip
-		shift
-		num_devices=$(adb devices | wc -l)
-		# no devices connected	
-		if [ $num_devices -eq 2 ]
-			then
-			echo "adb: no device connected please connect DUT via usb and try again..."
-		
-		# only 1 device - either wifi or usb
-		elif [ $num_devices -eq 3 ]
-			then
-			if adb devices | grep $ip &> /dev/null
-				then
-				echo "adb: DUT connected via wifi..."
-				is_connected=0
-			elif adb devices | grep $DUT &> /dev/null
-				then
-				echo "adb: DUT not connected via wifi, connecting..."
-				adb tcpip 5555
-				echo "Connection succeeded, Please disconnect phone from usb... <Enter>"
-				read
-				adb connect $ip
-				is_connected=$?
-				if [ $is_connected -eq 0 ]
-					then
-					echo "Connection succeeded..."
-					read
-				else
-					echo "Connection failed, please try again..."
-					exit 1
-				fi
-			fi
-		# DUT connected via usb AND wifi
-		elif [ $num_devices -eq 4 ] && adb devices | grep $ip &> /dev/null && adb devices | grep $DUT &> /dev/null
-			then
-			echo "adb: DUT is connected via usb and wifi"
-			echo "Please disconnect phone from usb... <Enter>"
-			read
-		fi
-		;;
+            ip=$1 # second argument is ip
+            shift
+            num_devices=$(adb devices | wc -l)
+            # no devices connected	
+            if [ $num_devices -eq 2 ]
+                    then
+                    echo "adb: no device connected please connect DUT via usb and try again..."
+            
+            # only 1 device - either wifi or usb
+            elif [ $num_devices -eq 3 ]
+                    then
+                    if adb devices | grep $ip &> /dev/null
+                            then
+                            echo "adb: DUT connected via wifi..."
+                            is_connected=0
+                    elif adb devices | grep $DUT &> /dev/null
+                            then
+                            echo "adb: DUT not connected via wifi, connecting..."
+                            adb tcpip 5555
+                            echo "Connection succeeded, Please disconnect phone from usb... <Enter>"
+                            read
+                            adb connect $ip
+                            is_connected=$?
+                            if [ $is_connected -eq 0 ]
+                                    then
+                                    echo "Connection succeeded..."
+                            else
+                                    echo "Connection failed, please try again..."
+                                    exit 1
+                            fi
+                    fi
+            # DUT connected via usb AND wifi
+            elif [ $num_devices -eq 4 ] && adb devices | grep $ip &> /dev/null && adb devices | grep $DUT &> /dev/null
+                    then
+                    echo "adb: DUT is connected via usb and wifi"
+                    echo "Please disconnect phone from usb... <Enter>"
+                    read
+            fi
+            ;;
 	
 	usb )
-		
-		if [ $num_devices -eq 2 ]
-             then
-             echo "adb: no device connected please connect DUT via usb and try again..."
-        elif [ $num_devices -eq 3 ] && adb devices | grep $DUT
-			then
-			echo "adb: DUT connected via usb..."
-			is_connected=0
-		else
-			echo "Too many devices connected, disconnect DUT from wifi..."
-			exit 1
-		fi
-		;;
+            if [ $num_devices -eq 2 ]
+                then
+                echo "adb: no device connected please connect DUT via usb and try again..."
+            
+            elif [ $num_devices -eq 3 ] && adb devices | grep $DUT
+		then
+		echo "adb: DUT connected via usb..."
+		is_connected=0
+	    else
+		echo "Too many devices connected, disconnect DUT from wifi..."
+		exit 1
+	    fi
+	    ;;
 
 esac
 
 if [ $is_connected -eq 0 ]
 	then
-	slash run -o log.console_level=0 tests/basic_suite/BasicTests.py $@
+	slash run -o log.console_level=0 tests/basic_suite/BasicTests.py "$@"
 fi
 
 exit 0
